baseurl                  = "https://jliu.ca"                # Your domain name
languageCode             = "en-ca"
defaultContentLanguage   = "en"
isMultilingual           = false
title                    = "J.S. Liu"
theme                    = "sam"
enableEmoji              = true
pygmentsStyle            = "monokai"                        # https://help.farbox.com/pygments.html
pygmentsCodefences       = true
googleAnalytics          = "UA-50133489-2"                  # Tracking code, eg. "UA-111111111-1"

[params]
    dateform             = "Mon 2 Jan 2006"
    dateformfull         = "Mon 2 Jan 2006 15:04:05 EST"
    favicon              = "leaf.ico"
    homepage             = "main"                           # What to call the home page link
    footerText           = ""                               # JS (Jason) Liu 2020.

# Metadata for Open Graph and Twitter
    description          = "J.S. (Jason) Liu."              # Max 160 characters show in search results
    images               = ["tn.png"]                       # Image that shows on Twitter cards and Open Graph links to the site
    title                = "J.S. (Jason) Liu"

[[params.mainMenu]]
    link = "aboot"
    text = "Hello."

[[params.mainMenu]]
    link = "aboot"
    text = "I'm Jason."

[imaging]
    quality = 75